settings:
  title: ' CUET Connect Status Page'
  url: 'statuspage.cuetconnect.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: MainSite # unique identifier
    name: CUETCONNECT(MainSite)
    description: 'This is our main site! Being Served from Vercel! ' # default=empty
    url: 'https://cuetconnect.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ForumSite
    name: CUETCONNECT(ForumSite)
    description: 'Forum site for CUETians! Being served from FreeFlarum!'
    url: 'https://forum.cuetconnect.org/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: AdmissionSite
    name: CUETCONNECT(AdmissionSite)
    description: 'Site for admission releted info. Being served from Github Pages!'
    url: 'https://admission.cuetconnect.org/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: NoticesSite
    name: CUETCONNECT(NoticesSite)
    description: 'Site for general notices. Being served from Github Pages!'
    url: 'https://notices.cuetconnect.org/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: ShopSite
    name: CUETCONNECT(ShopSite)
    description: 'Wordpress Ecommerce site. Being served from a USA Datacenter !'
    url: 'https://shop.cuetconnect.org/'
    method: GET
    expectStatus: 200
    linkable: true

